version: '3'
services:
  product:
    image: pagonxt/product
    build: product
    ports:
      - 3000:3000
    
  account:
    image: pagonxt/account
    build: account
    volumes:
     - ./account:/app
    ports:
     - 3001:3000 
  
  account-database:
    image: mongo
    container_name: account-database
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=mongopass
      - MONGO_INITDB_DATABASE=accounts
    ports:
      - 27017:27017